// <auto-generated />
using MeetingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeetingApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241127000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeetingApp.Models.MeetingRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Lokation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Pladsantal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MeetingRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lokation = "1. sal, bygning Nord",
                            Navn = "Konferencesal A",
                            Pladsantal = 20
                        },
                        new
                        {
                            Id = 2,
                            Lokation = "Stueetagen, bygning Syd",
                            Navn = "Meeting Room B",
                            Pladsantal = 8
                        },
                        new
                        {
                            Id = 3,
                            Lokation = "2. sal, bygning Vest",
                            Navn = "Kreativt Rum",
                            Pladsantal = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
